// This file is automatically generated by qtc from "footer.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/admintemplates/footer.qtpl:1
package admintemplates

//line wasgood/templates/admintemplates/footer.qtpl:1
import "github.com/gin-gonic/gin"

//line wasgood/templates/admintemplates/footer.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/admintemplates/footer.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/admintemplates/footer.qtpl:3
func streamfooter(qw422016 *qt422016.Writer, c *gin.Context) {
	//line wasgood/templates/admintemplates/footer.qtpl:3
	qw422016.N().S(`
</div>
</div>
<!-- /span -->
</div>
<!-- /row -->
<!-- content ends -->
</div>
<!-- /#content.span10 -->
</div>
<!-- /fluid-row -->
<hr/>
<div class="modal hide fade" id="myModal">
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
		×
	</button>
	<h3>
		Settings
	</h3>
</div>
<div class="modal-body">
	<p>
		Here settings can be configured...
	</p>
</div>
<div class="modal-footer">
	<a href="#" class="btn" data-dismiss="modal">
		Close
	</a>
	<a href="#" class="btn btn-primary">
		Save changes
	</a>
</div>
</div>
<footer>
<small class="pull-right">
</small>
</footer>
</div>
<!-- /.fluid-container -->
<!-- external javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- jQuery -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:48
	streamurl(qw422016, "/admin/js/jquery-1.7.2.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:48
	qw422016.N().S(`"></script>
<!-- jQuery UI -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:50
	streamurl(qw422016, "/admin/js/jquery-ui-1.8.21.custom.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:50
	qw422016.N().S(`"></script>
<!-- transition / effect library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:52
	streamurl(qw422016, "/admin/js/bootstrap-transition.js")
	//line wasgood/templates/admintemplates/footer.qtpl:52
	qw422016.N().S(`"></script>
<!-- alert enhancer library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:54
	streamurl(qw422016, "/admin/js/bootstrap-alert.js")
	//line wasgood/templates/admintemplates/footer.qtpl:54
	qw422016.N().S(`"></script>
<!-- modal / dialog library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:56
	streamurl(qw422016, "/admin/js/bootstrap-modal.js")
	//line wasgood/templates/admintemplates/footer.qtpl:56
	qw422016.N().S(`"></script>
<!-- custom dropdown library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:58
	streamurl(qw422016, "/admin/js/bootstrap-dropdown.js")
	//line wasgood/templates/admintemplates/footer.qtpl:58
	qw422016.N().S(`"></script>
<!-- scrolspy library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:60
	streamurl(qw422016, "/admin/js/bootstrap-scrollspy.js")
	//line wasgood/templates/admintemplates/footer.qtpl:60
	qw422016.N().S(`"></script>
<!-- library for creating tabs -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:62
	streamurl(qw422016, "/admin/js/bootstrap-tab.js")
	//line wasgood/templates/admintemplates/footer.qtpl:62
	qw422016.N().S(`"></script>
<!-- library for advanced tooltip -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:64
	streamurl(qw422016, "/admin/js/bootstrap-tooltip.js")
	//line wasgood/templates/admintemplates/footer.qtpl:64
	qw422016.N().S(`"></script>
<!-- popover effect library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:66
	streamurl(qw422016, "/admin/js/bootstrap-popover.js")
	//line wasgood/templates/admintemplates/footer.qtpl:66
	qw422016.N().S(`"></script>
<!-- button enhancer library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:68
	streamurl(qw422016, "/admin/js/bootstrap-button.js")
	//line wasgood/templates/admintemplates/footer.qtpl:68
	qw422016.N().S(`"></script>
<!-- accordion library (optional, not used in demo) -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:70
	streamurl(qw422016, "/admin/js/bootstrap-collapse.js")
	//line wasgood/templates/admintemplates/footer.qtpl:70
	qw422016.N().S(`"></script>
<!-- carousel slideshow library (optional, not used in demo) -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:72
	streamurl(qw422016, "/admin/js/bootstrap-carousel.js")
	//line wasgood/templates/admintemplates/footer.qtpl:72
	qw422016.N().S(`"></script>
<!-- autocomplete library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:74
	streamurl(qw422016, "/admin/js/bootstrap-typeahead.js")
	//line wasgood/templates/admintemplates/footer.qtpl:74
	qw422016.N().S(`"></script>
<!-- tour library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:76
	streamurl(qw422016, "/admin/js/bootstrap-tour.js")
	//line wasgood/templates/admintemplates/footer.qtpl:76
	qw422016.N().S(`"></script>
<!-- library for cookie management -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:78
	streamurl(qw422016, "/admin/js/jquery.cookie.js")
	//line wasgood/templates/admintemplates/footer.qtpl:78
	qw422016.N().S(`"></script>
<!-- calendar plugin -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:80
	streamurl(qw422016, "/admin/js/fullcalendar.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:80
	qw422016.N().S(`"></script>
<!-- data table plugin -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:82
	streamurl(qw422016, "/admin/js/jquery.dataTables.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:82
	qw422016.N().S(`"></script>
<!-- chart libraries start -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:84
	streamurl(qw422016, "/admin/js/excanvas.js")
	//line wasgood/templates/admintemplates/footer.qtpl:84
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:85
	streamurl(qw422016, "/admin/js/jquery.flot.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:85
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:86
	streamurl(qw422016, "/admin/js/jquery.flot.pie.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:86
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:87
	streamurl(qw422016, "/admin/js/jquery.flot.stack.js")
	//line wasgood/templates/admintemplates/footer.qtpl:87
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:88
	streamurl(qw422016, "/admin/js/jquery.flot.resize.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:88
	qw422016.N().S(`"></script>
<!-- chart libraries end -->
<!-- select or dropdown enhancer -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:91
	streamurl(qw422016, "/admin/js/jquery.chosen.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:91
	qw422016.N().S(`"></script>
<!-- checkbox, radio, and file input styler -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:93
	streamurl(qw422016, "/admin/js/jquery.uniform.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:93
	qw422016.N().S(`"></script>
<!-- plugin for gallery image view -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:95
	streamurl(qw422016, "/admin/js/jquery.colorbox.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:95
	qw422016.N().S(`"></script>
<!-- rich text editor library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:97
	streamurl(qw422016, "/admin/js/wysihtml5.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:97
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:98
	streamurl(qw422016, "/admin/js/wysihtml5-parser.js")
	//line wasgood/templates/admintemplates/footer.qtpl:98
	qw422016.N().S(`"></script>
<!-- notification plugin -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:100
	streamurl(qw422016, "/admin/js/jquery.noty.js")
	//line wasgood/templates/admintemplates/footer.qtpl:100
	qw422016.N().S(`"></script>
<!-- file manager library -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:102
	streamurl(qw422016, "/admin/js/jquery.elfinder.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:102
	qw422016.N().S(`"></script>
<!-- star rating plugin -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:104
	streamurl(qw422016, "/admin/js/jquery.raty.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:104
	qw422016.N().S(`"></script>
<!-- for iOS style toggle switch -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:106
	streamurl(qw422016, "/admin/js/jquery.iphone.toggle.js")
	//line wasgood/templates/admintemplates/footer.qtpl:106
	qw422016.N().S(`"></script>
<!-- autogrowing textarea plugin -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:108
	streamurl(qw422016, "/admin/js/jquery.autogrow-textarea.js")
	//line wasgood/templates/admintemplates/footer.qtpl:108
	qw422016.N().S(`"></script>
<!-- multiple file upload plugin -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:110
	streamurl(qw422016, "/admin/js/jquery.uploadify-3.1.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:110
	qw422016.N().S(`"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:112
	streamurl(qw422016, "/admin/js/jquery.history.js")
	//line wasgood/templates/admintemplates/footer.qtpl:112
	qw422016.N().S(`"></script>
<!-- Form's input tags plugin -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:114
	streamurl(qw422016, "/admin/js/tag-it.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:114
	qw422016.N().S(`"></script>
<!-- application script for Charisma demo -->
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:116
	streamurl(qw422016, "/admin/js/charisma.js")
	//line wasgood/templates/admintemplates/footer.qtpl:116
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/admintemplates/footer.qtpl:117
	streamurl(qw422016, "/admin/js/jquery.serializejson.min.js")
	//line wasgood/templates/admintemplates/footer.qtpl:117
	qw422016.N().S(`"></script>
</body>
</html>
`)
//line wasgood/templates/admintemplates/footer.qtpl:120
}

//line wasgood/templates/admintemplates/footer.qtpl:120
func writefooter(qq422016 qtio422016.Writer, c *gin.Context) {
	//line wasgood/templates/admintemplates/footer.qtpl:120
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/admintemplates/footer.qtpl:120
	streamfooter(qw422016, c)
	//line wasgood/templates/admintemplates/footer.qtpl:120
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/admintemplates/footer.qtpl:120
}

//line wasgood/templates/admintemplates/footer.qtpl:120
func footer(c *gin.Context) string {
	//line wasgood/templates/admintemplates/footer.qtpl:120
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/admintemplates/footer.qtpl:120
	writefooter(qb422016, c)
	//line wasgood/templates/admintemplates/footer.qtpl:120
	qs422016 := string(qb422016.B)
	//line wasgood/templates/admintemplates/footer.qtpl:120
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/admintemplates/footer.qtpl:120
	return qs422016
//line wasgood/templates/admintemplates/footer.qtpl:120
}
