// This file is automatically generated by qtc from "header.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/admintemplates/header.qtpl:1
package admintemplates

//line wasgood/templates/admintemplates/header.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"wasgood/app"
	"wasgood/models"
)

//line wasgood/templates/admintemplates/header.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/admintemplates/header.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/admintemplates/header.qtpl:7
func streamurl(qw422016 *qt422016.Writer, path string) {
	//line wasgood/templates/admintemplates/header.qtpl:7
	qw422016.E().S(app.RootURL)
	//line wasgood/templates/admintemplates/header.qtpl:7
	qw422016.E().S(path)
//line wasgood/templates/admintemplates/header.qtpl:7
}

//line wasgood/templates/admintemplates/header.qtpl:7
func writeurl(qq422016 qtio422016.Writer, path string) {
	//line wasgood/templates/admintemplates/header.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/admintemplates/header.qtpl:7
	streamurl(qw422016, path)
	//line wasgood/templates/admintemplates/header.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/admintemplates/header.qtpl:7
}

//line wasgood/templates/admintemplates/header.qtpl:7
func url(path string) string {
	//line wasgood/templates/admintemplates/header.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/admintemplates/header.qtpl:7
	writeurl(qb422016, path)
	//line wasgood/templates/admintemplates/header.qtpl:7
	qs422016 := string(qb422016.B)
	//line wasgood/templates/admintemplates/header.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/admintemplates/header.qtpl:7
	return qs422016
//line wasgood/templates/admintemplates/header.qtpl:7
}

//line wasgood/templates/admintemplates/header.qtpl:9
func streamheader(qw422016 *qt422016.Writer, c *gin.Context) {
	//line wasgood/templates/admintemplates/header.qtpl:9
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Admin</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Admin panel">

	<!-- The styles -->
	<link id="bs-css" href="`)
	//line wasgood/templates/admintemplates/header.qtpl:19
	streamurl(qw422016, "/admin/css/bootstrap-classic.css")
	//line wasgood/templates/admintemplates/header.qtpl:19
	qw422016.N().S(`" rel="stylesheet">
	<style type="text/css">
	  body {
		padding-bottom: 40px;
	  }
	  .sidebar-nav {
		padding: 9px 0;
	  }
	</style>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:28
	streamurl(qw422016, "/admin/css/bootstrap-responsive.css")
	//line wasgood/templates/admintemplates/header.qtpl:28
	qw422016.N().S(`" rel="stylesheet">
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:29
	streamurl(qw422016, "/admin/css/charisma-app.css")
	//line wasgood/templates/admintemplates/header.qtpl:29
	qw422016.N().S(`" rel="stylesheet">
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:30
	streamurl(qw422016, "/admin/css/jquery-ui-1.8.21.custom.css")
	//line wasgood/templates/admintemplates/header.qtpl:30
	qw422016.N().S(`" rel="stylesheet">
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:31
	streamurl(qw422016, "/admin/css/fullcalendar.css")
	//line wasgood/templates/admintemplates/header.qtpl:31
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:32
	streamurl(qw422016, "/admin/css/fullcalendar.print.css")
	//line wasgood/templates/admintemplates/header.qtpl:32
	qw422016.N().S(`" rel='stylesheet'  media='print'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:33
	streamurl(qw422016, "/admin/css/chosen.css")
	//line wasgood/templates/admintemplates/header.qtpl:33
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:34
	streamurl(qw422016, "/admin/css/uniform.default.css")
	//line wasgood/templates/admintemplates/header.qtpl:34
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:35
	streamurl(qw422016, "/admin/css/colorbox.css")
	//line wasgood/templates/admintemplates/header.qtpl:35
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:36
	streamurl(qw422016, "/admin/css/jquery.cleditor.css")
	//line wasgood/templates/admintemplates/header.qtpl:36
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:37
	streamurl(qw422016, "/admin/css/jquery.noty.css")
	//line wasgood/templates/admintemplates/header.qtpl:37
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:38
	streamurl(qw422016, "/admin/css/noty_theme_default.css")
	//line wasgood/templates/admintemplates/header.qtpl:38
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:39
	streamurl(qw422016, "/admin/css/elfinder.min.css")
	//line wasgood/templates/admintemplates/header.qtpl:39
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:40
	streamurl(qw422016, "/admin/css/elfinder.theme.css")
	//line wasgood/templates/admintemplates/header.qtpl:40
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:41
	streamurl(qw422016, "/admin/css/jquery.iphone.toggle.css")
	//line wasgood/templates/admintemplates/header.qtpl:41
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:42
	streamurl(qw422016, "/admin/css/opa-icons.css")
	//line wasgood/templates/admintemplates/header.qtpl:42
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:43
	streamurl(qw422016, "/admin/css/uploadify.css")
	//line wasgood/templates/admintemplates/header.qtpl:43
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:44
	streamurl(qw422016, "/admin/css/jquery.tagit.css")
	//line wasgood/templates/admintemplates/header.qtpl:44
	qw422016.N().S(`" rel='stylesheet'>
	<link href="`)
	//line wasgood/templates/admintemplates/header.qtpl:45
	streamurl(qw422016, "/admin/css/wysihtml5.css")
	//line wasgood/templates/admintemplates/header.qtpl:45
	qw422016.N().S(`" rel='stylesheet'>

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- The fav icon -->
	<link rel="shortcut icon" href="`)
	//line wasgood/templates/admintemplates/header.qtpl:53
	streamurl(qw422016, "/admin/img/favicon.ico")
	//line wasgood/templates/admintemplates/header.qtpl:53
	qw422016.N().S(`">
		
</head>

<body>
	<div id="cleditor-panel" style="display:none;">
		<li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="p">¶</li>
		<li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1">H1</li>
		<li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2">H2</li>
		<li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h3">H3</li>
		<li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h4">H4</li>
	  <li data-wysihtml5-command="formatInline" data-wysihtml5-command-value="strong" class="icon-bold"> </li>
	  <li data-wysihtml5-command="formatInline" data-wysihtml5-command-value="i" class="icon-italic"> </li>
	  <li data-wysihtml5-command="formatInline" data-wysihtml5-command-value="u" style="text-decoration:underline;">U</li>
	  <li data-wysihtml5-command="insertUnorderedList" class="icon-th-list" title="list"> </li>
	  <li data-wysihtml5-command="createLink" class="icon-hand-up" title="link"> </li>
	  <div data-wysihtml5-dialog="createLink" style="display: none;">
	    <label>
	      Link:
	      <input data-wysihtml5-dialog-field="href" value="http://" class="text">
	    </label>
	    <a data-wysihtml5-dialog-action="save">OK</a> <a data-wysihtml5-dialog-action="cancel">Cancel</a>
	  </div>
	  <li data-wysihtml5-command="insertImage" class="icon-picture"> </li>
	  	<div data-wysihtml5-dialog="insertImage" style="display: none;">
			<label>
				Image:
				<input data-wysihtml5-dialog-field="src" value="http://">
			</label>
			<a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
		</div>
		<li data-wysihtml5-action="change_view">HTML</li>
	</div>

	<!-- topbar starts -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="`)
	//line wasgood/templates/admintemplates/header.qtpl:96
	streamurl(qw422016, "/admin")
	//line wasgood/templates/admintemplates/header.qtpl:96
	qw422016.N().S(`"> Admin <img src="`)
	//line wasgood/templates/admintemplates/header.qtpl:96
	qw422016.E().S(models.GetUserFromContext(c).Photo)
	//line wasgood/templates/admintemplates/header.qtpl:96
	qw422016.N().S(`"/></a>
				
				<div class="pull-right" style="line-height: 40px">
					По любым вопросам обращайтесь в <a href="https://vk.com/nezashlo" target="_blank">vk.com/nezashlo</a>
				</div>
				`)
	//line wasgood/templates/admintemplates/header.qtpl:123
	qw422016.N().S(`
			</div>
		</div>
	</div>
	<!-- topbar ends -->
	
	<div class="container-fluid">
		<div class="row-fluid">		
			<!-- left menu starts -->
			<div class="span2 main-menu-span">
				<div class="well nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li><a class="ajax-link" href="`)
	//line wasgood/templates/admintemplates/header.qtpl:135
	streamurl(qw422016, "/admin/liquids/1")
	//line wasgood/templates/admintemplates/header.qtpl:135
	qw422016.N().S(`"><i class="icon-tint"></i><span class="hidden-tablet"> Liquid</span></a>
							<ul class="nav nav-pills nav-stacked">
								<li><a class="ajax-link" href="`)
	//line wasgood/templates/admintemplates/header.qtpl:137
	streamurl(qw422016, "/admin/liquids/new")
	//line wasgood/templates/admintemplates/header.qtpl:137
	qw422016.N().S(`"><i class="icon-plus-sign"></i><span class="hidden-tablet"> Add Liquid</span></a></li>
							</ul>
						</li>
						<li><a class="ajax-link" href="`)
	//line wasgood/templates/admintemplates/header.qtpl:140
	streamurl(qw422016, "/admin/reviews")
	//line wasgood/templates/admintemplates/header.qtpl:140
	qw422016.N().S(`"><i class="icon-comment"></i><span class="hidden-tablet"> Reviews</span></a></li>
						<li><a class="ajax-link" href="`)
	//line wasgood/templates/admintemplates/header.qtpl:141
	streamurl(qw422016, "/admin/tags")
	//line wasgood/templates/admintemplates/header.qtpl:141
	qw422016.N().S(`"><i class="icon-tags"></i><span class="hidden-tablet"> Tags</span></a></li>
					</ul>
				</div><!--/.well -->
			</div><!--/span-->
			<!-- left menu ends -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			
			<div id="content" class="span10">
			<!-- content starts -->
			
			<div class="row-fluid">
				<div class="box span12">
					<div class="box-content">
`)
//line wasgood/templates/admintemplates/header.qtpl:160
}

//line wasgood/templates/admintemplates/header.qtpl:160
func writeheader(qq422016 qtio422016.Writer, c *gin.Context) {
	//line wasgood/templates/admintemplates/header.qtpl:160
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/admintemplates/header.qtpl:160
	streamheader(qw422016, c)
	//line wasgood/templates/admintemplates/header.qtpl:160
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/admintemplates/header.qtpl:160
}

//line wasgood/templates/admintemplates/header.qtpl:160
func header(c *gin.Context) string {
	//line wasgood/templates/admintemplates/header.qtpl:160
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/admintemplates/header.qtpl:160
	writeheader(qb422016, c)
	//line wasgood/templates/admintemplates/header.qtpl:160
	qs422016 := string(qb422016.B)
	//line wasgood/templates/admintemplates/header.qtpl:160
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/admintemplates/header.qtpl:160
	return qs422016
//line wasgood/templates/admintemplates/header.qtpl:160
}
