// This file is automatically generated by qtc from "liquid.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/admintemplates/liquid.qtpl:1
package admintemplates

//line wasgood/templates/admintemplates/liquid.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"wasgood/models"
)

//line wasgood/templates/admintemplates/liquid.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/admintemplates/liquid.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/admintemplates/liquid.qtpl:6
func StreamLiquid(qw422016 *qt422016.Writer, c *gin.Context, item *models.Liquid) {
	//line wasgood/templates/admintemplates/liquid.qtpl:6
	qw422016.N().S(`

`)
	//line wasgood/templates/admintemplates/liquid.qtpl:8
	streamheader(qw422016, c)
	//line wasgood/templates/admintemplates/liquid.qtpl:8
	qw422016.N().S(`

<form data-type="json" class="form-horizontal" method="POST" enctype="multipart/form-data">
	<fieldset>
		<legend>
			Liquid
		</legend>
		`)
	//line wasgood/templates/admintemplates/liquid.qtpl:15
	streamitemPart(qw422016, &item.Item)
	//line wasgood/templates/admintemplates/liquid.qtpl:15
	qw422016.N().S(`
		<div class="span7">
			<div class="control-group">
				<label class="control-label">
					<a href="`)
	//line wasgood/templates/admintemplates/liquid.qtpl:19
	streamurl(qw422016, "/admin/tags")
	//line wasgood/templates/admintemplates/liquid.qtpl:19
	qw422016.N().S(`">Flavors</a>
				</label>
				<div class="controls">
					<select multiple data-rel="chosen" name="flavors[]" class="span7">
						`)
	//line wasgood/templates/admintemplates/liquid.qtpl:23
	for _, flavor := range models.GetAllTagsForField("flavors") {
		//line wasgood/templates/admintemplates/liquid.qtpl:23
		qw422016.N().S(`
						<option value="`)
		//line wasgood/templates/admintemplates/liquid.qtpl:24
		qw422016.N().D(flavor.ID)
		//line wasgood/templates/admintemplates/liquid.qtpl:24
		qw422016.N().S(`"
						`)
		//line wasgood/templates/admintemplates/liquid.qtpl:25
		for _, iflavor := range item.Flavors {
			//line wasgood/templates/admintemplates/liquid.qtpl:25
			qw422016.N().S(`
							`)
			//line wasgood/templates/admintemplates/liquid.qtpl:26
			if flavor.ID == iflavor.ID {
				//line wasgood/templates/admintemplates/liquid.qtpl:26
				qw422016.N().S(`
								selected
							`)
				//line wasgood/templates/admintemplates/liquid.qtpl:28
			}
			//line wasgood/templates/admintemplates/liquid.qtpl:28
			qw422016.N().S(`
						`)
			//line wasgood/templates/admintemplates/liquid.qtpl:29
		}
		//line wasgood/templates/admintemplates/liquid.qtpl:29
		qw422016.N().S(`
						>`)
		//line wasgood/templates/admintemplates/liquid.qtpl:30
		qw422016.E().S(flavor.Name)
		//line wasgood/templates/admintemplates/liquid.qtpl:30
		qw422016.N().S(`
						</option>
						`)
		//line wasgood/templates/admintemplates/liquid.qtpl:32
	}
	//line wasgood/templates/admintemplates/liquid.qtpl:32
	qw422016.N().S(`
					</select>
				</div>
			</div>
		</div>

		<div class="form-actions span11">
			<div class="span7">
				<button type="submit" class="btn btn-primary">
					Save changes
				</button>
			</div>
			<div class="span2">
				<span class="icon-arrow-left">
				</span>
				<a href="`)
	//line wasgood/templates/admintemplates/liquid.qtpl:47
	streamurl(qw422016, "/admin/liquids/")
	//line wasgood/templates/admintemplates/liquid.qtpl:47
	qw422016.N().D(item.ID - 1)
	//line wasgood/templates/admintemplates/liquid.qtpl:47
	qw422016.N().S(`">
					Prev
				</a>
			</div>
			<div class="span2">
				<a href="`)
	//line wasgood/templates/admintemplates/liquid.qtpl:52
	streamurl(qw422016, "/admin/liquids/")
	//line wasgood/templates/admintemplates/liquid.qtpl:52
	qw422016.N().D(item.ID + 1)
	//line wasgood/templates/admintemplates/liquid.qtpl:52
	qw422016.N().S(`">
					Next
				</a>
				<span class="icon-arrow-right">
				</span>
			</div>
		</div>
	</fieldset>
</form>

`)
	//line wasgood/templates/admintemplates/liquid.qtpl:62
	streamfooter(qw422016, c)
	//line wasgood/templates/admintemplates/liquid.qtpl:62
	qw422016.N().S(`

`)
//line wasgood/templates/admintemplates/liquid.qtpl:64
}

//line wasgood/templates/admintemplates/liquid.qtpl:64
func WriteLiquid(qq422016 qtio422016.Writer, c *gin.Context, item *models.Liquid) {
	//line wasgood/templates/admintemplates/liquid.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/admintemplates/liquid.qtpl:64
	StreamLiquid(qw422016, c, item)
	//line wasgood/templates/admintemplates/liquid.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/admintemplates/liquid.qtpl:64
}

//line wasgood/templates/admintemplates/liquid.qtpl:64
func Liquid(c *gin.Context, item *models.Liquid) string {
	//line wasgood/templates/admintemplates/liquid.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/admintemplates/liquid.qtpl:64
	WriteLiquid(qb422016, c, item)
	//line wasgood/templates/admintemplates/liquid.qtpl:64
	qs422016 := string(qb422016.B)
	//line wasgood/templates/admintemplates/liquid.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/admintemplates/liquid.qtpl:64
	return qs422016
//line wasgood/templates/admintemplates/liquid.qtpl:64
}
