// This file is automatically generated by qtc from "reviews.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/admintemplates/reviews.qtpl:1
package admintemplates

//line wasgood/templates/admintemplates/reviews.qtpl:1
import (
	"github.com/gin-gonic/gin"
)

//line wasgood/templates/admintemplates/reviews.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/admintemplates/reviews.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/admintemplates/reviews.qtpl:5
func StreamUnapprovedReviews(qw422016 *qt422016.Writer, c *gin.Context, reviews map[int][]int) {
	//line wasgood/templates/admintemplates/reviews.qtpl:5
	qw422016.N().S(`
`)
	//line wasgood/templates/admintemplates/reviews.qtpl:6
	streamheader(qw422016, c)
	//line wasgood/templates/admintemplates/reviews.qtpl:6
	qw422016.N().S(`
<table class="table table-condensed">
	<thead>
		<tr><th>Item ID</th><th>Reviews IDs</th></tr>
	</thead>
	<tbody>
	`)
	//line wasgood/templates/admintemplates/reviews.qtpl:12
	for itemID, reviewIDs := range reviews {
		//line wasgood/templates/admintemplates/reviews.qtpl:12
		qw422016.N().S(`
		<tr>
			<td>`)
		//line wasgood/templates/admintemplates/reviews.qtpl:14
		qw422016.N().D(itemID)
		//line wasgood/templates/admintemplates/reviews.qtpl:14
		qw422016.N().S(`</td>
			<td class="center">
				`)
		//line wasgood/templates/admintemplates/reviews.qtpl:16
		for _, ID := range reviewIDs {
			//line wasgood/templates/admintemplates/reviews.qtpl:16
			qw422016.N().S(`
					<a href="`)
			//line wasgood/templates/admintemplates/reviews.qtpl:17
			streamurl(qw422016, "/items/")
			//line wasgood/templates/admintemplates/reviews.qtpl:17
			qw422016.N().D(itemID)
			//line wasgood/templates/admintemplates/reviews.qtpl:17
			qw422016.N().S(`#review-`)
			//line wasgood/templates/admintemplates/reviews.qtpl:17
			qw422016.N().D(ID)
			//line wasgood/templates/admintemplates/reviews.qtpl:17
			qw422016.N().S(`">`)
			//line wasgood/templates/admintemplates/reviews.qtpl:17
			qw422016.N().D(ID)
			//line wasgood/templates/admintemplates/reviews.qtpl:17
			qw422016.N().S(`</a> 
				`)
			//line wasgood/templates/admintemplates/reviews.qtpl:18
		}
		//line wasgood/templates/admintemplates/reviews.qtpl:18
		qw422016.N().S(`
			</td>
		</tr>
	`)
		//line wasgood/templates/admintemplates/reviews.qtpl:21
	}
	//line wasgood/templates/admintemplates/reviews.qtpl:21
	qw422016.N().S(`
	</tbody>
</table>
`)
	//line wasgood/templates/admintemplates/reviews.qtpl:24
	streamfooter(qw422016, c)
	//line wasgood/templates/admintemplates/reviews.qtpl:24
	qw422016.N().S(`
`)
//line wasgood/templates/admintemplates/reviews.qtpl:25
}

//line wasgood/templates/admintemplates/reviews.qtpl:25
func WriteUnapprovedReviews(qq422016 qtio422016.Writer, c *gin.Context, reviews map[int][]int) {
	//line wasgood/templates/admintemplates/reviews.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/admintemplates/reviews.qtpl:25
	StreamUnapprovedReviews(qw422016, c, reviews)
	//line wasgood/templates/admintemplates/reviews.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/admintemplates/reviews.qtpl:25
}

//line wasgood/templates/admintemplates/reviews.qtpl:25
func UnapprovedReviews(c *gin.Context, reviews map[int][]int) string {
	//line wasgood/templates/admintemplates/reviews.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/admintemplates/reviews.qtpl:25
	WriteUnapprovedReviews(qb422016, c, reviews)
	//line wasgood/templates/admintemplates/reviews.qtpl:25
	qs422016 := string(qb422016.B)
	//line wasgood/templates/admintemplates/reviews.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/admintemplates/reviews.qtpl:25
	return qs422016
//line wasgood/templates/admintemplates/reviews.qtpl:25
}
