// This file is automatically generated by qtc from "tags.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/admintemplates/tags.qtpl:1
package admintemplates

//line wasgood/templates/admintemplates/tags.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"wasgood/models"
)

//line wasgood/templates/admintemplates/tags.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/admintemplates/tags.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/admintemplates/tags.qtpl:6
func StreamTags(qw422016 *qt422016.Writer, c *gin.Context, tags map[int]*models.Tag) {
	//line wasgood/templates/admintemplates/tags.qtpl:6
	qw422016.N().S(`

`)
	//line wasgood/templates/admintemplates/tags.qtpl:8
	streamheader(qw422016, c)
	//line wasgood/templates/admintemplates/tags.qtpl:8
	qw422016.N().S(`

<table class="table table-condensed">
	<thead>
		<tr><th>Tag ID</th><th>Name</th><th>Slug</th><th></th></tr>
	</thead>
	<tbody>
	`)
	//line wasgood/templates/admintemplates/tags.qtpl:15
	for _, tag := range tags {
		//line wasgood/templates/admintemplates/tags.qtpl:15
		qw422016.N().S(`
		<tr>
			<td>`)
		//line wasgood/templates/admintemplates/tags.qtpl:17
		qw422016.N().D(tag.ID)
		//line wasgood/templates/admintemplates/tags.qtpl:17
		qw422016.N().S(`</td>
			<td>`)
		//line wasgood/templates/admintemplates/tags.qtpl:18
		qw422016.E().S(tag.Name)
		//line wasgood/templates/admintemplates/tags.qtpl:18
		qw422016.N().S(`</td>
			<td>`)
		//line wasgood/templates/admintemplates/tags.qtpl:19
		qw422016.E().S(tag.Slug)
		//line wasgood/templates/admintemplates/tags.qtpl:19
		qw422016.N().S(`</td>
			<td class="center">
				<a class="btn btn-success" href="`)
		//line wasgood/templates/admintemplates/tags.qtpl:21
		streamurl(qw422016, "/admin/tags/")
		//line wasgood/templates/admintemplates/tags.qtpl:21
		qw422016.N().D(tag.ID)
		//line wasgood/templates/admintemplates/tags.qtpl:21
		qw422016.N().S(`">
					<i class="icon-edit icon-white"></i>  
				</a>
			</td>
		</tr>
	`)
		//line wasgood/templates/admintemplates/tags.qtpl:26
	}
	//line wasgood/templates/admintemplates/tags.qtpl:26
	qw422016.N().S(`
	</tbody>
</table>

`)
	//line wasgood/templates/admintemplates/tags.qtpl:30
	streamfooter(qw422016, c)
	//line wasgood/templates/admintemplates/tags.qtpl:30
	qw422016.N().S(`

`)
//line wasgood/templates/admintemplates/tags.qtpl:32
}

//line wasgood/templates/admintemplates/tags.qtpl:32
func WriteTags(qq422016 qtio422016.Writer, c *gin.Context, tags map[int]*models.Tag) {
	//line wasgood/templates/admintemplates/tags.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/admintemplates/tags.qtpl:32
	StreamTags(qw422016, c, tags)
	//line wasgood/templates/admintemplates/tags.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/admintemplates/tags.qtpl:32
}

//line wasgood/templates/admintemplates/tags.qtpl:32
func Tags(c *gin.Context, tags map[int]*models.Tag) string {
	//line wasgood/templates/admintemplates/tags.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/admintemplates/tags.qtpl:32
	WriteTags(qb422016, c, tags)
	//line wasgood/templates/admintemplates/tags.qtpl:32
	qs422016 := string(qb422016.B)
	//line wasgood/templates/admintemplates/tags.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/admintemplates/tags.qtpl:32
	return qs422016
//line wasgood/templates/admintemplates/tags.qtpl:32
}
