// This file is automatically generated by qtc from "footer.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/footer.qtpl:1
package templates

//line wasgood/templates/footer.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"time"
	"wasgood/app"
	"wasgood/models"
)

//line wasgood/templates/footer.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/footer.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/footer.qtpl:8
func streamfooter(qw422016 *qt422016.Writer, c *gin.Context, p *Page) {
	//line wasgood/templates/footer.qtpl:8
	qw422016.N().S(`
`)
	//line wasgood/templates/footer.qtpl:10
	user := models.GetUserFromContext(c)
	year := time.Now().Year()

	//line wasgood/templates/footer.qtpl:12
	qw422016.N().S(`
<div class="uk-margin uk-flex uk-flex-space-between footer">
	<div class="copyright uk-text-muted">
	© `)
	//line wasgood/templates/footer.qtpl:15
	qw422016.N().D(year)
	//line wasgood/templates/footer.qtpl:15
	qw422016.N().S(`, `)
	//line wasgood/templates/footer.qtpl:15
	qw422016.E().S(app.SiteName)
	//line wasgood/templates/footer.qtpl:15
	qw422016.N().S(`
	</div>
	<div class="social">
	обсуждение и общение - <a href="https://vk.com/nezashlo" class="uk-text-bold" target="_blank"><i class="uk-icon-vk"></i>/nezashlo</a>
	</div>
</div>
</div> <!-- container -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="`)
	//line wasgood/templates/footer.qtpl:23
	streamurl(qw422016, "/js/jquery.popupoverlay.js")
	//line wasgood/templates/footer.qtpl:23
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/footer.qtpl:24
	streamurl(qw422016, "/js/js.cookie.js")
	//line wasgood/templates/footer.qtpl:24
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/footer.qtpl:25
	streamurl(qw422016, "/js/uikit.js")
	//line wasgood/templates/footer.qtpl:25
	qw422016.N().S(`"></script>
<script defer src="`)
	//line wasgood/templates/footer.qtpl:26
	streamurl(qw422016, "/js/functions.js")
	//line wasgood/templates/footer.qtpl:26
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/footer.qtpl:27
	streamurl(qw422016, "/js/components/search.js")
	//line wasgood/templates/footer.qtpl:27
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/footer.qtpl:28
	streamurl(qw422016, "/js/components/lightbox.js")
	//line wasgood/templates/footer.qtpl:28
	qw422016.N().S(`"></script>
<script src="`)
	//line wasgood/templates/footer.qtpl:29
	streamurl(qw422016, "/js/components/autocomplete.js")
	//line wasgood/templates/footer.qtpl:29
	qw422016.N().S(`"></script>
`)
	//line wasgood/templates/footer.qtpl:30
	if user != nil && user.Provider == models.VK {
		//line wasgood/templates/footer.qtpl:30
		qw422016.N().S(`
<div id="vk_api_transport"></div>
<script type="text/javascript">
window.vkAsyncInit = function() {
	VK.init({
		apiId: 5589322
	});
	posttowall = function(message, attachments) {
		VK.api('wall.post', {
			message: message,
			attachments: attachments
		}, function(r) {});
	}
};

setTimeout(function() {
	var el = document.createElement("script");
	el.type = "text/javascript";
	el.src = "//vk.com/js/api/openapi.js";
	el.async = true;
	document.getElementById("vk_api_transport").appendChild(el);
}, 0);
</script>
`)
		//line wasgood/templates/footer.qtpl:53
	}
	//line wasgood/templates/footer.qtpl:53
	qw422016.N().S(`
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter40458210 = new Ya.Metrika({ id:40458210, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/40458210" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->

<!-- Vegetatika.ru tracker -->
<script type="text/javascript">
(function(d,b,ce,ac) {
var a=d[ce]("script");a.type="text/javascript";a.async=!0;
a.src="//vegetatika.ru/t.js";d[b][ac](a);
})(document,"body","createElement","appendChild");
</script>
<!-- /Vegetatika.ru tracker -->
</body>
</html>
`)
//line wasgood/templates/footer.qtpl:66
}

//line wasgood/templates/footer.qtpl:66
func writefooter(qq422016 qtio422016.Writer, c *gin.Context, p *Page) {
	//line wasgood/templates/footer.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/footer.qtpl:66
	streamfooter(qw422016, c, p)
	//line wasgood/templates/footer.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/footer.qtpl:66
}

//line wasgood/templates/footer.qtpl:66
func footer(c *gin.Context, p *Page) string {
	//line wasgood/templates/footer.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/footer.qtpl:66
	writefooter(qb422016, c, p)
	//line wasgood/templates/footer.qtpl:66
	qs422016 := string(qb422016.B)
	//line wasgood/templates/footer.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/footer.qtpl:66
	return qs422016
//line wasgood/templates/footer.qtpl:66
}
