// This file is automatically generated by qtc from "header.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/header.qtpl:1
package templates

//line wasgood/templates/header.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"wasgood/app"
	"wasgood/models"
)

//line wasgood/templates/header.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/header.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/header.qtpl:7
func streamurl(qw422016 *qt422016.Writer, path string) {
	//line wasgood/templates/header.qtpl:7
	qw422016.E().S(app.RootURL)
	//line wasgood/templates/header.qtpl:7
	qw422016.E().S(path)
//line wasgood/templates/header.qtpl:7
}

//line wasgood/templates/header.qtpl:7
func writeurl(qq422016 qtio422016.Writer, path string) {
	//line wasgood/templates/header.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/header.qtpl:7
	streamurl(qw422016, path)
	//line wasgood/templates/header.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/header.qtpl:7
}

//line wasgood/templates/header.qtpl:7
func url(path string) string {
	//line wasgood/templates/header.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/header.qtpl:7
	writeurl(qb422016, path)
	//line wasgood/templates/header.qtpl:7
	qs422016 := string(qb422016.B)
	//line wasgood/templates/header.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/header.qtpl:7
	return qs422016
//line wasgood/templates/header.qtpl:7
}

//line wasgood/templates/header.qtpl:9
func streamheader(qw422016 *qt422016.Writer, c *gin.Context, p *Page) {
	//line wasgood/templates/header.qtpl:9
	qw422016.N().S(`

`)
	//line wasgood/templates/header.qtpl:11
	user := models.GetUserFromContext(c)

	//line wasgood/templates/header.qtpl:11
	qw422016.N().S(`
<!doctype html>
<head>
  <meta charset="utf-8">
		<title>`)
	//line wasgood/templates/header.qtpl:15
	qw422016.E().S(p.Title)
	//line wasgood/templates/header.qtpl:15
	qw422016.N().S(` - `)
	//line wasgood/templates/header.qtpl:15
	qw422016.E().S(app.SiteName)
	//line wasgood/templates/header.qtpl:15
	qw422016.N().S(`</title>
		`)
	//line wasgood/templates/header.qtpl:16
	if p.Description != "" {
		//line wasgood/templates/header.qtpl:16
		qw422016.N().S(`<meta name="description" content="`)
		//line wasgood/templates/header.qtpl:16
		qw422016.E().S(p.Description)
		//line wasgood/templates/header.qtpl:16
		qw422016.N().S(`">`)
		//line wasgood/templates/header.qtpl:16
	}
	//line wasgood/templates/header.qtpl:16
	qw422016.N().S(`
		`)
	//line wasgood/templates/header.qtpl:17
	if p.Keywords != "" {
		//line wasgood/templates/header.qtpl:17
		qw422016.N().S(`<meta name="keywords" content="`)
		//line wasgood/templates/header.qtpl:17
		qw422016.E().S(p.Keywords)
		//line wasgood/templates/header.qtpl:17
		qw422016.N().S(`">`)
		//line wasgood/templates/header.qtpl:17
	}
	//line wasgood/templates/header.qtpl:17
	qw422016.N().S(`
		`)
	//line wasgood/templates/header.qtpl:18
	if p.OgImage != "" {
		//line wasgood/templates/header.qtpl:18
		qw422016.N().S(`<meta name="og:image" content="`)
		//line wasgood/templates/header.qtpl:18
		qw422016.E().S(p.OgImage)
		//line wasgood/templates/header.qtpl:18
		qw422016.N().S(`">`)
		//line wasgood/templates/header.qtpl:18
	}
	//line wasgood/templates/header.qtpl:18
	qw422016.N().S(`

		<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=cyrillic" rel="stylesheet">

		<link rel="stylesheet" href="`)
	//line wasgood/templates/header.qtpl:22
	streamurl(qw422016, "/css/uikit.css")
	//line wasgood/templates/header.qtpl:22
	qw422016.N().S(`" />
		<link rel="stylesheet" href="`)
	//line wasgood/templates/header.qtpl:23
	streamurl(qw422016, "/css/components/search.css")
	//line wasgood/templates/header.qtpl:23
	qw422016.N().S(`" />
		<link rel="stylesheet" href="`)
	//line wasgood/templates/header.qtpl:24
	streamurl(qw422016, "/css/components/slidenav.css")
	//line wasgood/templates/header.qtpl:24
	qw422016.N().S(`" />

		<link rel="stylesheet" href="`)
	//line wasgood/templates/header.qtpl:26
	streamurl(qw422016, "/css/style.css")
	//line wasgood/templates/header.qtpl:26
	qw422016.N().S(`" />

		<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
		<link rel="manifest" href="/manifest.json">
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
		<meta name="theme-color" content="#ffffff">

		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!--[if lt IE 9]>
			<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
		<![endif]-->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
</head>
<body `)
	//line wasgood/templates/header.qtpl:54
	if user != nil {
		//line wasgood/templates/header.qtpl:54
		qw422016.N().S(`data-user-id="`)
		//line wasgood/templates/header.qtpl:54
		qw422016.N().D(user.ID)
		//line wasgood/templates/header.qtpl:54
		qw422016.N().S(`"`)
		//line wasgood/templates/header.qtpl:54
	}
	//line wasgood/templates/header.qtpl:54
	qw422016.N().S(`>

`)
	//line wasgood/templates/header.qtpl:56
	if user == nil {
		//line wasgood/templates/header.qtpl:56
		qw422016.N().S(`
<div class="popup uk-panel uk-panel-box uk-grid uk-grid-collapse uk-flex-space-between">
	<div class="uk-panel-title">Чтобы голосовать, авторизуйтесь:</div>
	<div class="login-vk uk-width-1-2 uk-text-center">
		<a class="uk-button uk-button-primary" href="`)
		//line wasgood/templates/header.qtpl:60
		streamurl(qw422016, "/auth/vk/login")
		//line wasgood/templates/header.qtpl:60
		qw422016.N().S(`?redirect=`)
		//line wasgood/templates/header.qtpl:60
		qw422016.N().U(c.Request.URL.String())
		//line wasgood/templates/header.qtpl:60
		qw422016.N().S(`" title="Sign in with VK">
			Войти через <i class="uk-icon-vk"></i>
		</a>
	</div>
	<div class="login-fb uk-width-1-2 uk-text-center">
		<a class="uk-button uk-button-primary" href="`)
		//line wasgood/templates/header.qtpl:65
		streamurl(qw422016, "/auth/fb/login")
		//line wasgood/templates/header.qtpl:65
		qw422016.N().S(`?redirect=`)
		//line wasgood/templates/header.qtpl:65
		qw422016.N().U(c.Request.URL.String())
		//line wasgood/templates/header.qtpl:65
		qw422016.N().S(`" title="Sign in with Facebook">
			Войти через <i class="uk-icon-facebook-square"></i>
		</a>
	</div>
</div>
`)
		//line wasgood/templates/header.qtpl:70
	}
	//line wasgood/templates/header.qtpl:70
	qw422016.N().S(`

`)
	//line wasgood/templates/header.qtpl:72
	for _, flash := range p.Flashes {
		//line wasgood/templates/header.qtpl:72
		qw422016.N().S(`
<div class="uk-alert uk-alert-large uk-notify uk-notify-top-center" data-uk-alert="">
	<a class="uk-alert-close uk-close"></a>
	<p><strong>OK</strong> - `)
		//line wasgood/templates/header.qtpl:75
		qw422016.E().S(flash.(string))
		//line wasgood/templates/header.qtpl:75
		qw422016.N().S(`</p>
</div>
`)
		//line wasgood/templates/header.qtpl:77
	}
	//line wasgood/templates/header.qtpl:77
	qw422016.N().S(`

<div class="uk-container uk-container-center">
	<div class="header uk-grid uk-flex uk-margin-top uk-grid-small">
		<div class="uk-width-1-10 logo uk-hidden-small"><a href="`)
	//line wasgood/templates/header.qtpl:81
	streamurl(qw422016, "")
	//line wasgood/templates/header.qtpl:81
	qw422016.N().S(`"><img src="`)
	//line wasgood/templates/header.qtpl:81
	streamurl(qw422016, "/apple-icon-72x72.png")
	//line wasgood/templates/header.qtpl:81
	qw422016.N().S(`"/></a></div>
		<div class="uk-width-2-10 sitename uk-h1"><a href="`)
	//line wasgood/templates/header.qtpl:82
	streamurl(qw422016, "/")
	//line wasgood/templates/header.qtpl:82
	qw422016.N().S(`" class="no-decoration">`)
	//line wasgood/templates/header.qtpl:82
	qw422016.E().S(app.SiteName)
	//line wasgood/templates/header.qtpl:82
	qw422016.N().S(`</a></div>
		`)
	//line wasgood/templates/header.qtpl:83
	if user != nil {
		//line wasgood/templates/header.qtpl:83
		qw422016.N().S(`
		<div class="user uk-width-8-10 uk-width-medium-3-10 uk-push-4-10">
			<div class="photo uk-align-right"><img src="`)
		//line wasgood/templates/header.qtpl:85
		qw422016.E().S(user.Photo)
		//line wasgood/templates/header.qtpl:85
		qw422016.N().S(`"></div>
			<div class="uk-align-right uk-text-right">
				<div class="username">`)
		//line wasgood/templates/header.qtpl:87
		qw422016.E().S(user.Name)
		//line wasgood/templates/header.qtpl:87
		qw422016.N().S(`</div>
				<div class="logout uk-text-small uk-text-muted"><a href="`)
		//line wasgood/templates/header.qtpl:88
		streamurl(qw422016, "/auth/logout")
		//line wasgood/templates/header.qtpl:88
		qw422016.N().S(`?redirect=`)
		//line wasgood/templates/header.qtpl:88
		qw422016.N().U(c.Request.URL.String())
		//line wasgood/templates/header.qtpl:88
		qw422016.N().S(`">Выход</a></div>
				`)
		//line wasgood/templates/header.qtpl:89
		if user.Provider == models.VK {
			//line wasgood/templates/header.qtpl:89
			qw422016.N().S(`
					<div class="toombler uk-text-small">расшаривать в <i class="uk-icon-vk"></i> <input name="sharing" type="checkbox" class="local" checked></div>
				`)
			//line wasgood/templates/header.qtpl:91
		}
		//line wasgood/templates/header.qtpl:91
		qw422016.N().S(`
			</div>
		</div>
		`)
		//line wasgood/templates/header.qtpl:94
	} else {
		//line wasgood/templates/header.qtpl:94
		qw422016.N().S(`
		<div class="uk-width-8-10 uk-width-medium-3-10 uk-push-4-10 uk-flex uk-flex-right">
			<div class="login-vk">
				<a class="uk-button uk-button-primary" href="`)
		//line wasgood/templates/header.qtpl:97
		streamurl(qw422016, "/auth/vk/login")
		//line wasgood/templates/header.qtpl:97
		qw422016.N().S(`?redirect=`)
		//line wasgood/templates/header.qtpl:97
		qw422016.N().U(c.Request.URL.String())
		//line wasgood/templates/header.qtpl:97
		qw422016.N().S(`" title="Sign in with VK">
					Войти <span class="uk-hidden-small">через</span> <i class="uk-icon-vk"></i>
				</a>
			</div>
			<div class="login-fb uk-hidden">
				<a class="uk-button uk-button-primary" href="`)
		//line wasgood/templates/header.qtpl:102
		streamurl(qw422016, "/auth/fb/login")
		//line wasgood/templates/header.qtpl:102
		qw422016.N().S(`?redirect=`)
		//line wasgood/templates/header.qtpl:102
		qw422016.N().U(c.Request.URL.String())
		//line wasgood/templates/header.qtpl:102
		qw422016.N().S(`" title="Sign in with Facebook">
					Войти через <i class="uk-icon-facebook-square"></i>
				</a>
			</div>
		</div>
		`)
		//line wasgood/templates/header.qtpl:107
	}
	//line wasgood/templates/header.qtpl:107
	qw422016.N().S(`
		<div class="uk-width-1-1 uk-width-medium-4-10 uk-pull-3-10 search">
			<form class="uk-search" data-uk-search action="`)
	//line wasgood/templates/header.qtpl:109
	streamurl(qw422016, "/search")
	//line wasgood/templates/header.qtpl:109
	qw422016.N().S(`" method="GET">
				<div class="uk-grid uk-grid-small">
					<div class="uk-width-4-5 uk-autocomplete" data-uk-dropdown="{justify:'.uk-search-field', mode:'none'}" data-uk-autocomplete>
						<input class="uk-search-field" name="q" type="search" placeholder="жидкость, бренд или вкус..." pattern=".{3,}" required title="мин 3 символа">
						<div class="uk-dropdown ajax-search-results"></div>
					</div>
					<div class="uk-width-1-5">
						<input type="submit" class="uk-button" value="поиск">
					</div>
				</div>

			</form>
		</div>
	</div>
	<nav class="uk-navbar uk-width-1-1 uk-flex uk-flex-center uk-margin">
		<ul class="uk-navbar-nav">
			<li data-active class="uk-margin-right"><a href="`)
	//line wasgood/templates/header.qtpl:125
	streamurl(qw422016, "/rating/good")
	//line wasgood/templates/header.qtpl:125
	qw422016.N().S(`">Лучшие</a></li>
			<li data-active><a href="`)
	//line wasgood/templates/header.qtpl:126
	streamurl(qw422016, "/rating/bad")
	//line wasgood/templates/header.qtpl:126
	qw422016.N().S(`">Худшие</a></li>
		</ul>
	</nav>
`)
//line wasgood/templates/header.qtpl:129
}

//line wasgood/templates/header.qtpl:129
func writeheader(qq422016 qtio422016.Writer, c *gin.Context, p *Page) {
	//line wasgood/templates/header.qtpl:129
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/header.qtpl:129
	streamheader(qw422016, c, p)
	//line wasgood/templates/header.qtpl:129
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/header.qtpl:129
}

//line wasgood/templates/header.qtpl:129
func header(c *gin.Context, p *Page) string {
	//line wasgood/templates/header.qtpl:129
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/header.qtpl:129
	writeheader(qb422016, c, p)
	//line wasgood/templates/header.qtpl:129
	qs422016 := string(qb422016.B)
	//line wasgood/templates/header.qtpl:129
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/header.qtpl:129
	return qs422016
//line wasgood/templates/header.qtpl:129
}
