// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/index.qtpl:1
package templates

//line wasgood/templates/index.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"wasgood/models"
)

//line wasgood/templates/index.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/index.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/index.qtpl:7
type IndexPage struct {
	Page
	BestItems    []*models.Item
	WorstItems   []*models.Item
	BestBrands   []*models.Tag
	WorstBrands  []*models.Tag
	BestFlavors  []*models.Tag
	WorstFlavors []*models.Tag
}

//line wasgood/templates/index.qtpl:18
func streamtagRatingBlock(qw422016 *qt422016.Writer, tag *models.Tag, field string) {
	//line wasgood/templates/index.qtpl:18
	qw422016.N().S(`
<div class="uk-grid uk-grid-small uk-flex-middle uk-overflow-hidden">
	<div class="uk-width-1-6 thumbnail">
		<a href="`)
	//line wasgood/templates/index.qtpl:21
	streamurl(qw422016, "/"+field+"/")
	//line wasgood/templates/index.qtpl:21
	qw422016.E().S(tag.Slug)
	//line wasgood/templates/index.qtpl:21
	qw422016.N().S(`" title="`)
	//line wasgood/templates/index.qtpl:21
	qw422016.E().S(tag.Name)
	//line wasgood/templates/index.qtpl:21
	qw422016.N().S(`">
			<img src="`)
	//line wasgood/templates/index.qtpl:22
	if tag.Logo != "" {
		//line wasgood/templates/index.qtpl:22
		qw422016.E().S(tag.Logo)
		//line wasgood/templates/index.qtpl:22
	} else {
		//line wasgood/templates/index.qtpl:22
		streamurl(qw422016, "/images/bottle-200x200.png")
		//line wasgood/templates/index.qtpl:22
	}
	//line wasgood/templates/index.qtpl:22
	qw422016.N().S(`" alt="`)
	//line wasgood/templates/index.qtpl:22
	qw422016.E().S(tag.Name)
	//line wasgood/templates/index.qtpl:22
	qw422016.N().S(`" class="uk-border-rounded" />
		</a>
	</div>
	<div class="uk-width-3-6">
		<div>
			<a href="`)
	//line wasgood/templates/index.qtpl:27
	streamurl(qw422016, "/"+field+"/")
	//line wasgood/templates/index.qtpl:27
	qw422016.E().S(tag.Slug)
	//line wasgood/templates/index.qtpl:27
	qw422016.N().S(`" title="`)
	//line wasgood/templates/index.qtpl:27
	qw422016.E().S(tag.Name)
	//line wasgood/templates/index.qtpl:27
	qw422016.N().S(`" class="uk-h4 uk-text-bold no-decoration name">
				`)
	//line wasgood/templates/index.qtpl:28
	qw422016.E().S(tag.Name)
	//line wasgood/templates/index.qtpl:28
	qw422016.N().S(`
			</a>
		</div>
	</div>
	<div class="uk-width-2-6 uk-flex uk-flex-top uk-flex-right">
		<div class="total uk-margin-small-left
			`)
	//line wasgood/templates/index.qtpl:34
	if tag.Rating > 0 {
		//line wasgood/templates/index.qtpl:34
		qw422016.N().S(`uk-text-success`)
		//line wasgood/templates/index.qtpl:34
	} else if tag.Rating < 0 {
		//line wasgood/templates/index.qtpl:34
		qw422016.N().S(`uk-text-danger`)
		//line wasgood/templates/index.qtpl:34
	}
	//line wasgood/templates/index.qtpl:34
	qw422016.N().S(` uk-h3 uk-text-bold">`)
	//line wasgood/templates/index.qtpl:34
	qw422016.N().D(tag.Rating)
	//line wasgood/templates/index.qtpl:34
	qw422016.N().S(`</div>
	</div>
</div>
`)
//line wasgood/templates/index.qtpl:37
}

//line wasgood/templates/index.qtpl:37
func writetagRatingBlock(qq422016 qtio422016.Writer, tag *models.Tag, field string) {
	//line wasgood/templates/index.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/index.qtpl:37
	streamtagRatingBlock(qw422016, tag, field)
	//line wasgood/templates/index.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/index.qtpl:37
}

//line wasgood/templates/index.qtpl:37
func tagRatingBlock(tag *models.Tag, field string) string {
	//line wasgood/templates/index.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/index.qtpl:37
	writetagRatingBlock(qb422016, tag, field)
	//line wasgood/templates/index.qtpl:37
	qs422016 := string(qb422016.B)
	//line wasgood/templates/index.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/index.qtpl:37
	return qs422016
//line wasgood/templates/index.qtpl:37
}

//line wasgood/templates/index.qtpl:39
func StreamIndex(qw422016 *qt422016.Writer, c *gin.Context, p *IndexPage) {
	//line wasgood/templates/index.qtpl:39
	qw422016.N().S(`
`)
	//line wasgood/templates/index.qtpl:40
	streamheader(qw422016, c, &p.Page)
	//line wasgood/templates/index.qtpl:40
	qw422016.N().S(`
<div class="content">
	<h2 class="uk-text-center">Жидкости</h2>
	<div class="uk-grid uk-grid-match">
		<div class="uk-width-medium-1-2 uk-margin-small-top">
			<div class="uk-panel uk-panel-box uk-panel-header rating-list">
				<div class="uk-panel-title">Лучшие</div>
				<div class="uk-panel-badge uk-badge uk-badge-success">TOP 10</div>
				`)
	//line wasgood/templates/index.qtpl:48
	for _, item := range p.BestItems {
		//line wasgood/templates/index.qtpl:48
		qw422016.N().S(`
					`)
		//line wasgood/templates/index.qtpl:49
		streamitemBlock(qw422016, item)
		//line wasgood/templates/index.qtpl:49
		qw422016.N().S(`
				`)
		//line wasgood/templates/index.qtpl:50
	}
	//line wasgood/templates/index.qtpl:50
	qw422016.N().S(`
				<hr>
				<a class="uk-align-right" href="`)
	//line wasgood/templates/index.qtpl:52
	streamurl(qw422016, "/rating/good")
	//line wasgood/templates/index.qtpl:52
	qw422016.N().S(`">все лучшие →</a>
			</div>
		</div>
		<div class="uk-width-medium-1-2 uk-margin-small-top">
			<div class="uk-panel uk-panel-box uk-panel-header rating-list">
				<div class="uk-panel-title">Худшие</div>
				<div class="uk-panel-badge uk-badge uk-badge-danger">TOP 10</div>
				`)
	//line wasgood/templates/index.qtpl:59
	for _, item := range p.WorstItems {
		//line wasgood/templates/index.qtpl:59
		qw422016.N().S(`
					`)
		//line wasgood/templates/index.qtpl:60
		streamitemBlock(qw422016, item)
		//line wasgood/templates/index.qtpl:60
		qw422016.N().S(`
				`)
		//line wasgood/templates/index.qtpl:61
	}
	//line wasgood/templates/index.qtpl:61
	qw422016.N().S(`
				<hr>
				<a class="uk-align-right" href="`)
	//line wasgood/templates/index.qtpl:63
	streamurl(qw422016, "/rating/bad")
	//line wasgood/templates/index.qtpl:63
	qw422016.N().S(`">все худшие →</a>
			</div>
		</div>
	</div>
	<h2 class="uk-text-center">Бренды</h2>
	<div class="uk-grid uk-grid-match">
		<div class="uk-width-medium-1-2 uk-margin-small-top">
			<div class="uk-panel uk-panel-box uk-panel-header rating-list">
				<div class="uk-panel-title">Лучшие</div>
				<div class="uk-panel-badge uk-badge uk-badge-success">TOP 10</div>
				`)
	//line wasgood/templates/index.qtpl:73
	for _, tag := range p.BestBrands {
		//line wasgood/templates/index.qtpl:73
		qw422016.N().S(`
					`)
		//line wasgood/templates/index.qtpl:74
		streamtagRatingBlock(qw422016, tag, "brand")
		//line wasgood/templates/index.qtpl:74
		qw422016.N().S(`
				`)
		//line wasgood/templates/index.qtpl:75
	}
	//line wasgood/templates/index.qtpl:75
	qw422016.N().S(`
			</div>
		</div>
		<div class="uk-width-medium-1-2 uk-margin-small-top">
			<div class="uk-panel uk-panel-box uk-panel-header rating-list">
				<div class="uk-panel-title">Худшие</div>
				<div class="uk-panel-badge uk-badge uk-badge-danger">TOP 10</div>
				`)
	//line wasgood/templates/index.qtpl:82
	for _, tag := range p.WorstBrands {
		//line wasgood/templates/index.qtpl:82
		qw422016.N().S(`
					`)
		//line wasgood/templates/index.qtpl:83
		streamtagRatingBlock(qw422016, tag, "brand")
		//line wasgood/templates/index.qtpl:83
		qw422016.N().S(`
				`)
		//line wasgood/templates/index.qtpl:84
	}
	//line wasgood/templates/index.qtpl:84
	qw422016.N().S(`
			</div>
		</div>
	</div>
	<h2 class="uk-text-center">Вкусы</h2>
	<div class="uk-grid uk-grid-match">
		<div class="uk-width-medium-1-2 uk-margin-small-top">
			<div class="uk-panel uk-panel-box uk-panel-header rating-list">
				<div class="uk-panel-title">Лучшие</div>
				<div class="uk-panel-badge uk-badge uk-badge-success">TOP 10</div>
				`)
	//line wasgood/templates/index.qtpl:94
	for _, tag := range p.BestFlavors {
		//line wasgood/templates/index.qtpl:94
		qw422016.N().S(`
					`)
		//line wasgood/templates/index.qtpl:95
		streamtagRatingBlock(qw422016, tag, "flavor")
		//line wasgood/templates/index.qtpl:95
		qw422016.N().S(`
				`)
		//line wasgood/templates/index.qtpl:96
	}
	//line wasgood/templates/index.qtpl:96
	qw422016.N().S(`
			</div>
		</div>
		<div class="uk-width-medium-1-2 uk-margin-small-top">
			<div class="uk-panel uk-panel-box uk-panel-header rating-list">
				<div class="uk-panel-title">Худшие</div>
				<div class="uk-panel-badge uk-badge uk-badge-danger">TOP 10</div>
				`)
	//line wasgood/templates/index.qtpl:103
	for _, tag := range p.WorstFlavors {
		//line wasgood/templates/index.qtpl:103
		qw422016.N().S(`
					`)
		//line wasgood/templates/index.qtpl:104
		streamtagRatingBlock(qw422016, tag, "flavor")
		//line wasgood/templates/index.qtpl:104
		qw422016.N().S(`
				`)
		//line wasgood/templates/index.qtpl:105
	}
	//line wasgood/templates/index.qtpl:105
	qw422016.N().S(`
			</div>
		</div>
	</div>
</div>
`)
	//line wasgood/templates/index.qtpl:110
	streamfooter(qw422016, c, &p.Page)
	//line wasgood/templates/index.qtpl:110
	qw422016.N().S(`
`)
//line wasgood/templates/index.qtpl:111
}

//line wasgood/templates/index.qtpl:111
func WriteIndex(qq422016 qtio422016.Writer, c *gin.Context, p *IndexPage) {
	//line wasgood/templates/index.qtpl:111
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/index.qtpl:111
	StreamIndex(qw422016, c, p)
	//line wasgood/templates/index.qtpl:111
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/index.qtpl:111
}

//line wasgood/templates/index.qtpl:111
func Index(c *gin.Context, p *IndexPage) string {
	//line wasgood/templates/index.qtpl:111
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/index.qtpl:111
	WriteIndex(qb422016, c, p)
	//line wasgood/templates/index.qtpl:111
	qs422016 := string(qb422016.B)
	//line wasgood/templates/index.qtpl:111
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/index.qtpl:111
	return qs422016
//line wasgood/templates/index.qtpl:111
}
