// This file is automatically generated by qtc from "search.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/search.qtpl:1
package templates

//line wasgood/templates/search.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"wasgood/models"
)

//line wasgood/templates/search.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/search.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/search.qtpl:7
type SearchResultsPage struct {
	Page
	Brands     map[int]*models.Tag
	Flavors    map[int]*models.Tag
	Items      []*models.Item
	PageNum    int
	IsLastPage bool
}

//line wasgood/templates/search.qtpl:17
func streamsearchTagBlock(qw422016 *qt422016.Writer, tag *models.Tag, field string) {
	//line wasgood/templates/search.qtpl:17
	qw422016.N().S(`
<div class="uk-width-medium-1-6 uk-width-1-3">
	<figure class="uk-overlay uk-overlay-hover">
		<img class="uk-overlay-scale" src="`)
	//line wasgood/templates/search.qtpl:20
	if tag.Logo != "" {
		//line wasgood/templates/search.qtpl:20
		qw422016.E().S(tag.Logo)
		//line wasgood/templates/search.qtpl:20
	} else {
		//line wasgood/templates/search.qtpl:20
		streamurl(qw422016, "/images/bottle-200x200.png")
		//line wasgood/templates/search.qtpl:20
	}
	//line wasgood/templates/search.qtpl:20
	qw422016.N().S(`" alt="`)
	//line wasgood/templates/search.qtpl:20
	qw422016.E().S(tag.Name)
	//line wasgood/templates/search.qtpl:20
	qw422016.N().S(`">
		<div class="uk-overlay-panel uk-overlay-background uk-overlay-bottom uk-ignore">
			<p>`)
	//line wasgood/templates/search.qtpl:22
	qw422016.E().S(tag.Name)
	//line wasgood/templates/search.qtpl:22
	qw422016.N().S(`</p>
		</div>
		<a class="uk-position-cover" href="`)
	//line wasgood/templates/search.qtpl:24
	streamurl(qw422016, "/"+field+"/")
	//line wasgood/templates/search.qtpl:24
	qw422016.E().S(tag.Slug)
	//line wasgood/templates/search.qtpl:24
	qw422016.N().S(`"></a>
	</figure>
</div>
`)
//line wasgood/templates/search.qtpl:27
}

//line wasgood/templates/search.qtpl:27
func writesearchTagBlock(qq422016 qtio422016.Writer, tag *models.Tag, field string) {
	//line wasgood/templates/search.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/search.qtpl:27
	streamsearchTagBlock(qw422016, tag, field)
	//line wasgood/templates/search.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/search.qtpl:27
}

//line wasgood/templates/search.qtpl:27
func searchTagBlock(tag *models.Tag, field string) string {
	//line wasgood/templates/search.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/search.qtpl:27
	writesearchTagBlock(qb422016, tag, field)
	//line wasgood/templates/search.qtpl:27
	qs422016 := string(qb422016.B)
	//line wasgood/templates/search.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/search.qtpl:27
	return qs422016
//line wasgood/templates/search.qtpl:27
}

//line wasgood/templates/search.qtpl:29
func streamsearchTagBlockRow(qw422016 *qt422016.Writer, tag *models.Tag, field string) {
	//line wasgood/templates/search.qtpl:29
	qw422016.N().S(`
<li><a class="uk-grid uk-grid-small uk-flex-middle uk-overflow-hidden tag" href="`)
	//line wasgood/templates/search.qtpl:30
	streamurl(qw422016, "/"+field+"/")
	//line wasgood/templates/search.qtpl:30
	qw422016.E().S(tag.Slug)
	//line wasgood/templates/search.qtpl:30
	qw422016.N().S(`">
	<div class="uk-width-1-6 thumbnail">
		<img src="`)
	//line wasgood/templates/search.qtpl:32
	if tag.Logo != "" {
		//line wasgood/templates/search.qtpl:32
		qw422016.E().S(tag.Logo)
		//line wasgood/templates/search.qtpl:32
	} else {
		//line wasgood/templates/search.qtpl:32
		streamurl(qw422016, "/images/bottle-200x200.png")
		//line wasgood/templates/search.qtpl:32
	}
	//line wasgood/templates/search.qtpl:32
	qw422016.N().S(`" alt="`)
	//line wasgood/templates/search.qtpl:32
	qw422016.E().S(tag.Name)
	//line wasgood/templates/search.qtpl:32
	qw422016.N().S(`" class="uk-border-rounded" />
	</div>
	<div class="uk-width-3-6">
		<div class="uk-h4 uk-text-bold no-decoration">
			`)
	//line wasgood/templates/search.qtpl:36
	qw422016.E().S(tag.Name)
	//line wasgood/templates/search.qtpl:36
	qw422016.N().S(`
		</div>
	</div>
	<div class="uk-width-2-6 uk-text-center">`)
	//line wasgood/templates/search.qtpl:39
	if field == "brand" {
		//line wasgood/templates/search.qtpl:39
		qw422016.N().S(`бренд`)
		//line wasgood/templates/search.qtpl:39
	} else if field == "flavor" {
		//line wasgood/templates/search.qtpl:39
		qw422016.N().S(`вкус`)
		//line wasgood/templates/search.qtpl:39
	}
	//line wasgood/templates/search.qtpl:39
	qw422016.N().S(`</div>
</a></li>
`)
//line wasgood/templates/search.qtpl:41
}

//line wasgood/templates/search.qtpl:41
func writesearchTagBlockRow(qq422016 qtio422016.Writer, tag *models.Tag, field string) {
	//line wasgood/templates/search.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/search.qtpl:41
	streamsearchTagBlockRow(qw422016, tag, field)
	//line wasgood/templates/search.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/search.qtpl:41
}

//line wasgood/templates/search.qtpl:41
func searchTagBlockRow(tag *models.Tag, field string) string {
	//line wasgood/templates/search.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/search.qtpl:41
	writesearchTagBlockRow(qb422016, tag, field)
	//line wasgood/templates/search.qtpl:41
	qs422016 := string(qb422016.B)
	//line wasgood/templates/search.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/search.qtpl:41
	return qs422016
//line wasgood/templates/search.qtpl:41
}

//line wasgood/templates/search.qtpl:43
func streamcondensedItemBlock(qw422016 *qt422016.Writer, item *models.Item) {
	//line wasgood/templates/search.qtpl:43
	qw422016.N().S(`
<li><a class="uk-grid uk-grid-small uk-flex-middle uk-overflow-hidden item `)
	//line wasgood/templates/search.qtpl:44
	if item.Hidden {
		//line wasgood/templates/search.qtpl:44
		qw422016.N().S(`hidden`)
		//line wasgood/templates/search.qtpl:44
	}
	//line wasgood/templates/search.qtpl:44
	qw422016.N().S(`" data-item-id="`)
	//line wasgood/templates/search.qtpl:44
	qw422016.N().D(item.ID)
	//line wasgood/templates/search.qtpl:44
	qw422016.N().S(`" title="`)
	//line wasgood/templates/search.qtpl:44
	qw422016.E().S(item.Brand.Name)
	//line wasgood/templates/search.qtpl:44
	qw422016.N().S(` / `)
	//line wasgood/templates/search.qtpl:44
	qw422016.E().S(item.Name)
	//line wasgood/templates/search.qtpl:44
	qw422016.N().S(`"
	href="`)
	//line wasgood/templates/search.qtpl:45
	streamurl(qw422016, "/liquids/")
	//line wasgood/templates/search.qtpl:45
	qw422016.N().D(item.ID)
	//line wasgood/templates/search.qtpl:45
	qw422016.N().S(`-`)
	//line wasgood/templates/search.qtpl:45
	qw422016.E().S(item.Slug())
	//line wasgood/templates/search.qtpl:45
	qw422016.N().S(`">
	<div class="uk-width-1-6 thumbnail">
		<img src="`)
	//line wasgood/templates/search.qtpl:47
	if len(item.Images) > 0 {
		//line wasgood/templates/search.qtpl:47
		qw422016.E().S(item.Images[0])
		//line wasgood/templates/search.qtpl:47
	} else {
		//line wasgood/templates/search.qtpl:47
		streamurl(qw422016, "/images/bottle-200x200.png")
		//line wasgood/templates/search.qtpl:47
	}
	//line wasgood/templates/search.qtpl:47
	qw422016.N().S(`" alt="`)
	//line wasgood/templates/search.qtpl:47
	qw422016.E().S(item.Brand.Name)
	//line wasgood/templates/search.qtpl:47
	qw422016.N().S(` / `)
	//line wasgood/templates/search.qtpl:47
	qw422016.E().S(item.Name)
	//line wasgood/templates/search.qtpl:47
	qw422016.N().S(`" class="uk-border-rounded" />
	</div>
	<div class="uk-width-3-6">
		<div class="uk-h4 uk-text-bold no-decoration name">
			`)
	//line wasgood/templates/search.qtpl:51
	qw422016.E().S(item.Name)
	//line wasgood/templates/search.qtpl:51
	qw422016.N().S(`
		</div>
		<div>
			<span class="uk-text-muted">от</span>
			<span class="brand">
				`)
	//line wasgood/templates/search.qtpl:56
	qw422016.E().S(item.Brand.Name)
	//line wasgood/templates/search.qtpl:56
	qw422016.N().S(`
			</span>
		</div>
	</div>
	<div class="uk-width-2-6 uk-text-center">жидкость</div>
</a></li>
`)
//line wasgood/templates/search.qtpl:62
}

//line wasgood/templates/search.qtpl:62
func writecondensedItemBlock(qq422016 qtio422016.Writer, item *models.Item) {
	//line wasgood/templates/search.qtpl:62
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/search.qtpl:62
	streamcondensedItemBlock(qw422016, item)
	//line wasgood/templates/search.qtpl:62
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/search.qtpl:62
}

//line wasgood/templates/search.qtpl:62
func condensedItemBlock(item *models.Item) string {
	//line wasgood/templates/search.qtpl:62
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/search.qtpl:62
	writecondensedItemBlock(qb422016, item)
	//line wasgood/templates/search.qtpl:62
	qs422016 := string(qb422016.B)
	//line wasgood/templates/search.qtpl:62
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/search.qtpl:62
	return qs422016
//line wasgood/templates/search.qtpl:62
}

//line wasgood/templates/search.qtpl:64
func StreamSearchResults(qw422016 *qt422016.Writer, c *gin.Context, p *SearchResultsPage) {
	//line wasgood/templates/search.qtpl:64
	qw422016.N().S(`
`)
	//line wasgood/templates/search.qtpl:65
	streamheader(qw422016, c, &p.Page)
	//line wasgood/templates/search.qtpl:65
	qw422016.N().S(`
<div class="content">
	`)
	//line wasgood/templates/search.qtpl:67
	if p.PageNum == 1 {
		//line wasgood/templates/search.qtpl:67
		qw422016.N().S(`
	<div class="uk-panel uk-panel-box uk-panel-header rating-list">
		<div class="uk-panel-title">Бренды "`)
		//line wasgood/templates/search.qtpl:69
		qw422016.E().S(p.Page.Title)
		//line wasgood/templates/search.qtpl:69
		qw422016.N().S(`"</div>
		<div class="uk-grid uk-grid-match" data-uk-grid-margin>
			`)
		//line wasgood/templates/search.qtpl:71
		for _, tag := range p.Brands {
			//line wasgood/templates/search.qtpl:71
			qw422016.N().S(`
				`)
			//line wasgood/templates/search.qtpl:72
			streamsearchTagBlock(qw422016, tag, "brand")
			//line wasgood/templates/search.qtpl:72
			qw422016.N().S(`
			`)
			//line wasgood/templates/search.qtpl:73
		}
		//line wasgood/templates/search.qtpl:73
		qw422016.N().S(`
		</div>
	</div>
	`)
		//line wasgood/templates/search.qtpl:76
	}
	//line wasgood/templates/search.qtpl:76
	qw422016.N().S(`
	`)
	//line wasgood/templates/search.qtpl:77
	if p.PageNum == 1 {
		//line wasgood/templates/search.qtpl:77
		qw422016.N().S(`
	<div class="uk-panel uk-panel-box uk-panel-header rating-list">
		<div class="uk-panel-title">Вкусы "`)
		//line wasgood/templates/search.qtpl:79
		qw422016.E().S(p.Page.Title)
		//line wasgood/templates/search.qtpl:79
		qw422016.N().S(`"</div>
		<div class="uk-grid uk-grid-match" data-uk-grid-margin>
			`)
		//line wasgood/templates/search.qtpl:81
		for _, tag := range p.Flavors {
			//line wasgood/templates/search.qtpl:81
			qw422016.N().S(`
				`)
			//line wasgood/templates/search.qtpl:82
			streamsearchTagBlock(qw422016, tag, "flavor")
			//line wasgood/templates/search.qtpl:82
			qw422016.N().S(`
			`)
			//line wasgood/templates/search.qtpl:83
		}
		//line wasgood/templates/search.qtpl:83
		qw422016.N().S(`
		</div>
	</div>
	`)
		//line wasgood/templates/search.qtpl:86
	}
	//line wasgood/templates/search.qtpl:86
	qw422016.N().S(`
	<div class="uk-panel uk-panel-box uk-panel-header rating-list">
		<div class="uk-panel-title">Жидкости "`)
	//line wasgood/templates/search.qtpl:88
	qw422016.E().S(p.Page.Title)
	//line wasgood/templates/search.qtpl:88
	qw422016.N().S(`"</div>
		`)
	//line wasgood/templates/search.qtpl:89
	for _, item := range p.Items {
		//line wasgood/templates/search.qtpl:89
		qw422016.N().S(`
			`)
		//line wasgood/templates/search.qtpl:90
		streamdetailedItemBlock(qw422016, item)
		//line wasgood/templates/search.qtpl:90
		qw422016.N().S(`
		`)
		//line wasgood/templates/search.qtpl:91
	}
	//line wasgood/templates/search.qtpl:91
	qw422016.N().S(`
	</div>
	<div class="pagination uk-width-1-1 uk-button-group uk-margin-large" data-pagenum="`)
	//line wasgood/templates/search.qtpl:93
	qw422016.N().D(p.PageNum)
	//line wasgood/templates/search.qtpl:93
	qw422016.N().S(`">
		<button class="uk-button uk-width-1-3 prev" `)
	//line wasgood/templates/search.qtpl:94
	if p.PageNum == 1 {
		//line wasgood/templates/search.qtpl:94
		qw422016.N().S(`disabled`)
		//line wasgood/templates/search.qtpl:94
	}
	//line wasgood/templates/search.qtpl:94
	qw422016.N().S(`><i class="uk-icon-arrow-left"></i> предыдущая</button>
		<button class="uk-button uk-width-1-3" disabled><span class="uk-hidden-small">страница </span>`)
	//line wasgood/templates/search.qtpl:95
	qw422016.N().D(p.PageNum)
	//line wasgood/templates/search.qtpl:95
	qw422016.N().S(`</button>
		<button class="uk-button uk-width-1-3 next" `)
	//line wasgood/templates/search.qtpl:96
	if p.IsLastPage {
		//line wasgood/templates/search.qtpl:96
		qw422016.N().S(`disabled`)
		//line wasgood/templates/search.qtpl:96
	}
	//line wasgood/templates/search.qtpl:96
	qw422016.N().S(`>следующая <i class="uk-icon-arrow-right"></i></button>
	</div>
</div>
`)
	//line wasgood/templates/search.qtpl:99
	streamfooter(qw422016, c, &p.Page)
	//line wasgood/templates/search.qtpl:99
	qw422016.N().S(`
`)
//line wasgood/templates/search.qtpl:100
}

//line wasgood/templates/search.qtpl:100
func WriteSearchResults(qq422016 qtio422016.Writer, c *gin.Context, p *SearchResultsPage) {
	//line wasgood/templates/search.qtpl:100
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/search.qtpl:100
	StreamSearchResults(qw422016, c, p)
	//line wasgood/templates/search.qtpl:100
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/search.qtpl:100
}

//line wasgood/templates/search.qtpl:100
func SearchResults(c *gin.Context, p *SearchResultsPage) string {
	//line wasgood/templates/search.qtpl:100
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/search.qtpl:100
	WriteSearchResults(qb422016, c, p)
	//line wasgood/templates/search.qtpl:100
	qs422016 := string(qb422016.B)
	//line wasgood/templates/search.qtpl:100
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/search.qtpl:100
	return qs422016
//line wasgood/templates/search.qtpl:100
}

//line wasgood/templates/search.qtpl:102
func StreamAjaxSearchResults(qw422016 *qt422016.Writer, c *gin.Context, p *SearchResultsPage) {
	//line wasgood/templates/search.qtpl:102
	qw422016.N().S(`
`)
	//line wasgood/templates/search.qtpl:104
	var items = 0

	//line wasgood/templates/search.qtpl:105
	qw422016.N().S(`

`)
	//line wasgood/templates/search.qtpl:107
	if len(p.Brands) > 0 {
		//line wasgood/templates/search.qtpl:107
		qw422016.N().S(`
<ul class="uk-list uk-margin-bottom-remove">
	`)
		//line wasgood/templates/search.qtpl:109
		for _, tag := range p.Brands {
			//line wasgood/templates/search.qtpl:109
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:110
			if items == 5 {
				//line wasgood/templates/search.qtpl:110
				qw422016.N().S(`
			`)
				//line wasgood/templates/search.qtpl:111
				break
				//line wasgood/templates/search.qtpl:112
			}
			//line wasgood/templates/search.qtpl:112
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:114
			items++

			//line wasgood/templates/search.qtpl:115
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:116
			streamsearchTagBlockRow(qw422016, tag, "brand")
			//line wasgood/templates/search.qtpl:116
			qw422016.N().S(`
	`)
			//line wasgood/templates/search.qtpl:117
		}
		//line wasgood/templates/search.qtpl:117
		qw422016.N().S(`
</ul>
`)
		//line wasgood/templates/search.qtpl:119
	}
	//line wasgood/templates/search.qtpl:119
	qw422016.N().S(`

`)
	//line wasgood/templates/search.qtpl:121
	if len(p.Brands) > 0 && (len(p.Flavors) > 0 || len(p.Items) > 0) {
		//line wasgood/templates/search.qtpl:121
		qw422016.N().S(`<hr/>`)
		//line wasgood/templates/search.qtpl:121
	}
	//line wasgood/templates/search.qtpl:121
	qw422016.N().S(`

`)
	//line wasgood/templates/search.qtpl:123
	if len(p.Flavors) > 0 {
		//line wasgood/templates/search.qtpl:123
		qw422016.N().S(`
<ul class="uk-list uk-margin-bottom-remove">
	`)
		//line wasgood/templates/search.qtpl:125
		for _, tag := range p.Flavors {
			//line wasgood/templates/search.qtpl:125
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:126
			if items == 10 {
				//line wasgood/templates/search.qtpl:126
				qw422016.N().S(`
			`)
				//line wasgood/templates/search.qtpl:127
				break
				//line wasgood/templates/search.qtpl:128
			}
			//line wasgood/templates/search.qtpl:128
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:130
			items++

			//line wasgood/templates/search.qtpl:131
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:132
			streamsearchTagBlockRow(qw422016, tag, "flavor")
			//line wasgood/templates/search.qtpl:132
			qw422016.N().S(`
	`)
			//line wasgood/templates/search.qtpl:133
		}
		//line wasgood/templates/search.qtpl:133
		qw422016.N().S(`
</ul>
`)
		//line wasgood/templates/search.qtpl:135
	}
	//line wasgood/templates/search.qtpl:135
	qw422016.N().S(`

`)
	//line wasgood/templates/search.qtpl:137
	if len(p.Flavors) > 0 && len(p.Items) > 0 {
		//line wasgood/templates/search.qtpl:137
		qw422016.N().S(`<hr/>`)
		//line wasgood/templates/search.qtpl:137
	}
	//line wasgood/templates/search.qtpl:137
	qw422016.N().S(`

`)
	//line wasgood/templates/search.qtpl:139
	if len(p.Items) > 0 {
		//line wasgood/templates/search.qtpl:139
		qw422016.N().S(`
<ul class="uk-list uk-margin-bottom-remove">
	`)
		//line wasgood/templates/search.qtpl:141
		for _, item := range p.Items {
			//line wasgood/templates/search.qtpl:141
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:142
			if items == 15 {
				//line wasgood/templates/search.qtpl:142
				qw422016.N().S(`
			`)
				//line wasgood/templates/search.qtpl:143
				break
				//line wasgood/templates/search.qtpl:144
			}
			//line wasgood/templates/search.qtpl:144
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:146
			items++

			//line wasgood/templates/search.qtpl:147
			qw422016.N().S(`
		`)
			//line wasgood/templates/search.qtpl:148
			streamcondensedItemBlock(qw422016, item)
			//line wasgood/templates/search.qtpl:148
			qw422016.N().S(`
	`)
			//line wasgood/templates/search.qtpl:149
		}
		//line wasgood/templates/search.qtpl:149
		qw422016.N().S(`
</ul>
`)
		//line wasgood/templates/search.qtpl:151
	}
	//line wasgood/templates/search.qtpl:151
	qw422016.N().S(`
`)
//line wasgood/templates/search.qtpl:152
}

//line wasgood/templates/search.qtpl:152
func WriteAjaxSearchResults(qq422016 qtio422016.Writer, c *gin.Context, p *SearchResultsPage) {
	//line wasgood/templates/search.qtpl:152
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/search.qtpl:152
	StreamAjaxSearchResults(qw422016, c, p)
	//line wasgood/templates/search.qtpl:152
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/search.qtpl:152
}

//line wasgood/templates/search.qtpl:152
func AjaxSearchResults(c *gin.Context, p *SearchResultsPage) string {
	//line wasgood/templates/search.qtpl:152
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/search.qtpl:152
	WriteAjaxSearchResults(qb422016, c, p)
	//line wasgood/templates/search.qtpl:152
	qs422016 := string(qb422016.B)
	//line wasgood/templates/search.qtpl:152
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/search.qtpl:152
	return qs422016
//line wasgood/templates/search.qtpl:152
}
