// This file is automatically generated by qtc from "tag.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line wasgood/templates/tag.qtpl:1
package templates

//line wasgood/templates/tag.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"wasgood/models"
)

//line wasgood/templates/tag.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line wasgood/templates/tag.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line wasgood/templates/tag.qtpl:7
type TagPage struct {
	Page
	Tag        *models.Tag
	Field      string
	Items      []*models.Item
	PageNum    int
	IsLastPage bool
}

//line wasgood/templates/tag.qtpl:17
func streamtagBlock(qw422016 *qt422016.Writer, tag *models.Tag, field string) {
	//line wasgood/templates/tag.qtpl:17
	qw422016.N().S(`
<div class="uk-panel-box uk-grid uk-flex-middle">
	<div class="uk-width-1-3 uk-text-center">
		<img class="uk-border-circle" src="`)
	//line wasgood/templates/tag.qtpl:20
	if tag.Logo != "" {
		//line wasgood/templates/tag.qtpl:20
		qw422016.E().S(tag.Logo)
		//line wasgood/templates/tag.qtpl:20
	} else {
		//line wasgood/templates/tag.qtpl:20
		streamurl(qw422016, "/images/bottle-200x200.png")
		//line wasgood/templates/tag.qtpl:20
	}
	//line wasgood/templates/tag.qtpl:20
	qw422016.N().S(`" alt="`)
	//line wasgood/templates/tag.qtpl:20
	qw422016.E().S(tag.Name)
	//line wasgood/templates/tag.qtpl:20
	qw422016.N().S(`" style="max-height: 200px;">
	</div>
	<div class="uk-width-2-3">
		<h2>`)
	//line wasgood/templates/tag.qtpl:23
	qw422016.E().S(tag.Name)
	//line wasgood/templates/tag.qtpl:23
	qw422016.N().S(`</h2>
		<p>`)
	//line wasgood/templates/tag.qtpl:24
	qw422016.N().S(tag.Description)
	//line wasgood/templates/tag.qtpl:24
	qw422016.N().S(`</p>
	</div>
</div>
`)
//line wasgood/templates/tag.qtpl:27
}

//line wasgood/templates/tag.qtpl:27
func writetagBlock(qq422016 qtio422016.Writer, tag *models.Tag, field string) {
	//line wasgood/templates/tag.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/tag.qtpl:27
	streamtagBlock(qw422016, tag, field)
	//line wasgood/templates/tag.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/tag.qtpl:27
}

//line wasgood/templates/tag.qtpl:27
func tagBlock(tag *models.Tag, field string) string {
	//line wasgood/templates/tag.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/tag.qtpl:27
	writetagBlock(qb422016, tag, field)
	//line wasgood/templates/tag.qtpl:27
	qs422016 := string(qb422016.B)
	//line wasgood/templates/tag.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/tag.qtpl:27
	return qs422016
//line wasgood/templates/tag.qtpl:27
}

//line wasgood/templates/tag.qtpl:29
func StreamTag(qw422016 *qt422016.Writer, c *gin.Context, p *TagPage) {
	//line wasgood/templates/tag.qtpl:29
	qw422016.N().S(`
`)
	//line wasgood/templates/tag.qtpl:30
	streamheader(qw422016, c, &p.Page)
	//line wasgood/templates/tag.qtpl:30
	qw422016.N().S(`
<div class="content">
	`)
	//line wasgood/templates/tag.qtpl:32
	streamtagBlock(qw422016, p.Tag, p.Field)
	//line wasgood/templates/tag.qtpl:32
	qw422016.N().S(`
	<div class="uk-panel uk-panel-box rating-list">
		`)
	//line wasgood/templates/tag.qtpl:34
	for _, item := range p.Items {
		//line wasgood/templates/tag.qtpl:34
		qw422016.N().S(`
			`)
		//line wasgood/templates/tag.qtpl:35
		streamdetailedItemBlock(qw422016, item)
		//line wasgood/templates/tag.qtpl:35
		qw422016.N().S(`
		`)
		//line wasgood/templates/tag.qtpl:36
	}
	//line wasgood/templates/tag.qtpl:36
	qw422016.N().S(`
	</div>
	<div class="pagination uk-width-1-1 uk-button-group uk-margin-large" data-pagenum="`)
	//line wasgood/templates/tag.qtpl:38
	qw422016.N().D(p.PageNum)
	//line wasgood/templates/tag.qtpl:38
	qw422016.N().S(`">
		<button class="uk-button uk-width-1-3 prev" `)
	//line wasgood/templates/tag.qtpl:39
	if p.PageNum == 1 {
		//line wasgood/templates/tag.qtpl:39
		qw422016.N().S(`disabled`)
		//line wasgood/templates/tag.qtpl:39
	}
	//line wasgood/templates/tag.qtpl:39
	qw422016.N().S(`><i class="uk-icon-arrow-left"></i> предыдущая</button>
		<button class="uk-button uk-width-1-3" disabled>страница `)
	//line wasgood/templates/tag.qtpl:40
	qw422016.N().D(p.PageNum)
	//line wasgood/templates/tag.qtpl:40
	qw422016.N().S(`</button>
		<button class="uk-button uk-width-1-3 next" `)
	//line wasgood/templates/tag.qtpl:41
	if p.IsLastPage {
		//line wasgood/templates/tag.qtpl:41
		qw422016.N().S(`disabled`)
		//line wasgood/templates/tag.qtpl:41
	}
	//line wasgood/templates/tag.qtpl:41
	qw422016.N().S(`>следующая <i class="uk-icon-arrow-right"></i></button>
	</div>
</div>
`)
	//line wasgood/templates/tag.qtpl:44
	streamfooter(qw422016, c, &p.Page)
	//line wasgood/templates/tag.qtpl:44
	qw422016.N().S(`
`)
//line wasgood/templates/tag.qtpl:45
}

//line wasgood/templates/tag.qtpl:45
func WriteTag(qq422016 qtio422016.Writer, c *gin.Context, p *TagPage) {
	//line wasgood/templates/tag.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line wasgood/templates/tag.qtpl:45
	StreamTag(qw422016, c, p)
	//line wasgood/templates/tag.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line wasgood/templates/tag.qtpl:45
}

//line wasgood/templates/tag.qtpl:45
func Tag(c *gin.Context, p *TagPage) string {
	//line wasgood/templates/tag.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
	//line wasgood/templates/tag.qtpl:45
	WriteTag(qb422016, c, p)
	//line wasgood/templates/tag.qtpl:45
	qs422016 := string(qb422016.B)
	//line wasgood/templates/tag.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
	//line wasgood/templates/tag.qtpl:45
	return qs422016
//line wasgood/templates/tag.qtpl:45
}
